POST http://localhost:3005/register HTTP/1.1
content-type: application/json

{
    "email": "sakti.voffifcefe@gmail.com",
    "password": "xero123",
    "first_name": "Kevin",
    "last_name": "Ramadhan",
    "current_base": "89",
    "dob": "2000-12-11",
    "phone": "087757764873832",
    "user_group": 89,
    "user_acl": {
        "invoicing": "1:1:1",
        "client": "1:1:1",
        "call_handling": "1:1:1",
        "mail_handling": "1:1:1",
        "visitor_handling": "1:1:1",
        "booking": "1:1:1",
        "product": "1:1:1",
        "location": "1:1:1",
        "serviced_office": "1:1:1",
        "deals": "1:1:1",
        "promo": "1:1:1",
        "created_by": 24
    }
}

###

POST http://localhost:3005/login HTTP/1.1
content-type: application/json

{
    "email": "saktivoffifcefe@gmail.com",
    "password": "xero123"
}

###

GET http://localhost:3005/products HTTP/1.1
Content-Type: application/application/json
Authorization: "Bearer "

###

POST http://localhost:3005/locations HTTP/1.1
content-type: application/json

{
    "name": "Green Office Park 6 BSD",
    "city": "BSD",
    "province": "Jawa Barat",
    "country": "Indonesia",
    "tax_id": "12345",
    "phone": "02123456789",
    "timezone": "asia/jakarta",
    "center_email": "bsd@voffice.co.id",
    "start_time": 700,
    "end_time": 1800,
    "weekend_start_time": 0,
    "weekend_end_time": 0,
    "coordinates": "-6.303249, 106.652715",
    "company_name": "Voffice BSD",
    "extension": "224455",
    "address": "bsd tangerang selatan",
    "status": "1",
    "created_by": 24
}
