POST http://localhost:3005/login HTTP/1.1
content-type: application/json

{
    "email": "testing@gmail.com",
    "password": "testing123"
}

###

POST http://localhost:3005/user-group HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImVtYWlsIjoidGVzdGluZ0BnbWFpbC5jb20iLCJpYXQiOjE2MDY4ODE2NDUsImV4cCI6MTYwNjkxMDQ0NX0.aEtyIdKVD1Cm0-FyIi1YTwk7SsfQrzWizyugo-xuxsg

{
    "name": "Lokiz"
}

###

PUT http://localhost:3005/user-group/3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImVtYWlsIjoidGVzdGluZ0BnbWFpbC5jb20iLCJpYXQiOjE2MDY4ODE2NDUsImV4cCI6MTYwNjkxMDQ0NX0.aEtyIdKVD1Cm0-FyIi1YTwk7SsfQrzWizyugo-xuxsg

{
    "name": "hahaha"
}

###

DELETE http://localhost:3005/user-group/3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImVtYWlsIjoidGVzdGluZ0BnbWFpbC5jb20iLCJpYXQiOjE2MDY4ODE2NDUsImV4cCI6MTYwNjkxMDQ0NX0.aEtyIdKVD1Cm0-FyIi1YTwk7SsfQrzWizyugo-xuxsg

###

GET http://localhost:3005/user-group/1 HTTP/1.1
content-type: application/json

###

GET http://localhost:3005/user-group/ HTTP/1.1
content-type: application/json

###

GET http://localhost:3005/products HTTP/1.1
Content-Type: application/application/json
Authorization: "Bearer "