POST http://localhost:3005/register HTTP/1.1
content-type: application/json

{
    "email": "theyudhiztira@gmail.com",
    "first_name": "Pandu",
    "last_name": "Yudhistira",
    "current_base": "89",
    "dob": "1995-02-18",
    "phone": "085155001616",
    "user_group": 89,
    "user_acl": 2
}