//CREATE
POST http://localhost:3005/clients HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZGV2dGVhbUB2b2ZmaWNlLmNvLmlkIiwiaWF0IjoxNjEwNDM5Mzk5LCJleHAiOjE2MTA0NjgxOTl9.FKuZApgs4mmoi4568tqg-bUgu-8uc24i1q-enj9X8a4

{
    "first_name": "Kevin",
    "last_name": "Ramadhan",
    "email": "sakti.f@gmail.com",
    "phone": "0871757421141878",
    "whatsapp": "087757764878",
    "business_needs": [1,2,3],
    "discovery_source": 1,
    "web_register": null
}

###
//GET
GET http://localhost:3005/clients?status=5 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZGV2dGVhbUB2b2ZmaWNlLmNvLmlkIiwiaWF0IjoxNjEwNTk1ODQ0LCJleHAiOjE2MTA2MjQ2NDR9.TR9LCwzI2UwptYh2mlNjrvp3wCGqMBGSVh9hwdg423I

{
    //
}

###
// UPDATE CLIENT BY client_id
PUT http://localhost:3005/clients/13 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImVtYWlsIjoiZGV2dGVhbUB2b2ZmaWNlLmNvLmlkIiwiaWF0IjoxNjEwNDM5Mzk5LCJleHAiOjE2MTA0NjgxOTl9.FKuZApgs4mmoi4568tqg-bUgu-8uc24i1q-enj9X8a4

{
    "first_name": "Kevin edit",
    "last_name": "Ramadhan edit",
    "email": "sakti.edit@gmail.com",
    "phone": "087175742114187800",
    "whatsapp": "08775776487800",
    "business_needs": [1,2,3,5],
    "discovery_source": 4,
    "web_register": 4,
    "status": "5"
}

###
// DELETE LOCATION BY location_id
DELETE http://localhost:3005/locations/3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3LCJlbWFpbCI6InRlc3RpbmdAZ21haWwuY29tIiwiaWF0IjoxNjA2ODgzNDI5LCJleHAiOjE2MDY5MTIyMjl9.CjN_vJOCMmynEW-rQowG2ySNnGk9QUQvwhfvFyAr7ZQ

{
    //
}