//CREATE
POST http://localhost:3005/locations HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjY2LCJlbWFpbCI6ImRldnRlYW1Adm9mZmljZS5jby5pZCIsImlhdCI6MTYwODAyMDI5MCwiZXhwIjoxNjA4MDQ5MDkwfQ.PurJdVj1fk070uGl8HzCtJ5tsllLMA3oWo3sXg-pnr8

{
    "name": "Green Office Park 6 BSD",
    "city": "BSD",
    "province": "Jawa Barat",
    "country": "Indonesia",
    "tax_id": "12345",
    "phone": "02123456789",
    "timezone": "asia/jakarta",
    "center_email": "bsd@voffice.co.id",
    "start_time": 700,
    "end_time": 1800,
    "weekend_start_time": 0,
    "weekend_end_time": 0,
    "coordinates": "-6.303249, 106.652715",
    "company_name": "Voffice BSD",
    "extension": "224455",
    "address": "bsd tangerang selatan",
    "status": "1"
}

###
//GET ALL
GET http://localhost:3005/locations HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjY2LCJlbWFpbCI6ImRldnRlYW1Adm9mZmljZS5jby5pZCIsImlhdCI6MTYwODAyMDI5MCwiZXhwIjoxNjA4MDQ5MDkwfQ.PurJdVj1fk070uGl8HzCtJ5tsllLMA3oWo3sXg-pnr8

{
    //
}

###
// GET SPECIFIC LOCATION BY location_id
GET http://localhost:3005/locations/8 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3LCJlbWFpbCI6InRlc3RpbmdAZ21haWwuY29tIiwiaWF0IjoxNjA2ODgzNDI5LCJleHAiOjE2MDY5MTIyMjl9.CjN_vJOCMmynEW-rQowG2ySNnGk9QUQvwhfvFyAr7ZQ

{
    //
}

###
// UPDATE LOCATION BY location_id
PUT http://localhost:3005/locations/8 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3LCJlbWFpbCI6InRlc3RpbmdAZ21haWwuY29tIiwiaWF0IjoxNjA2ODgzNDI5LCJleHAiOjE2MDY5MTIyMjl9.CjN_vJOCMmynEW-rQowG2ySNnGk9QUQvwhfvFyAr7ZQ

{
    "name": "Green Office Park 6 BSD edit",
    "city": "BSD edit",
    "province": "Jawa Barat edit",
    "country": "Indonesia edit",
    "tax_id": "12345 edit",
    "phone": "02123456789 edit",
    "timezone": "asia/jakarta edit",
    "center_email": "bsd@voffice.co.id edit",
    "start_time": 7006,
    "end_time": 18006,
    "weekend_start_time": 0,
    "weekend_end_time": 0,
    "coordinates": "-6.303249, 106.652715 edit",
    "company_name": "Voffice BSD edit",
    "extension": "224455 edit",
    "address": "bsd tangerang selatan edit",
    "status": "0"
}

###
// DELETE LOCATION BY location_id
DELETE http://localhost:3005/locations/3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjM3LCJlbWFpbCI6InRlc3RpbmdAZ21haWwuY29tIiwiaWF0IjoxNjA2ODgzNDI5LCJleHAiOjE2MDY5MTIyMjl9.CjN_vJOCMmynEW-rQowG2ySNnGk9QUQvwhfvFyAr7ZQ

{
    //
}