GET http://localhost:3005/products?page=2&pageSize=10 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImVtYWlsIjoidGVzdGluZ0BnbWFpbC5jb20iLCJpYXQiOjE2MDY4OTkwMTMsImV4cCI6MTYwNjkyNzgxM30.kH9i-fD1If0zxZvOOV_Jdy52itoz8G6ZteKXqAdc3g0
